#   
#   BSD 3-Clause License
#   
#   Copyright (c) 2020, Kurt Kennett
#   All rights reserved.
#   
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#   
#   1. Redistributions of source code must retain the above copyright notice, this
#      list of conditions and the following disclaimer.
#   
#   2. Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#   
#   3. Neither the name of the copyright holder nor the names of its
#      contributors may be used to endorse or promote products derived from
#      this software without specific prior written permission.
#   
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#   FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#   SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

include $(K2_ROOT)/src/shared/build/pre.make

TARGET_SPECIFIC_ARCH = A32
TARGET_TYPE = LIB

SOURCES += bp.s
SOURCES += dcache.s
SOURCES += icache.s
SOURCES += reg_auxctrl.s
SOURCES += reg_ccsidr.s
SOURCES += reg_clidr.s
SOURCES += reg_context.s
SOURCES += reg_cpacr.s
SOURCES += reg_csselr.s
SOURCES += reg_ctr.s
SOURCES += reg_dacr.s
SOURCES += reg_dfar.s
SOURCES += reg_dfsr.s
SOURCES += reg_idpfr.s
SOURCES += reg_ifar.s
SOURCES += reg_ifsr.s
SOURCES += reg_midr.s
SOURCES += reg_mpidr.s
SOURCES += reg_scr.s
SOURCES += reg_sctrl.s
SOURCES += reg_tpidr.s
SOURCES += reg_ttbr0.s
SOURCES += reg_ttbr1.s
SOURCES += reg_ttbcr.s
SOURCES += setints.s
SOURCES += tlb.s
SOURCES += trans.s
SOURCES += reg_cpsr.s
SOURCES += reg_cbar.s

include $(K2_ROOT)/src/shared/build/post.make


